// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6oR1BkXqqWpeX9-zBl5O_NjDG2DCdB8',
    appId: '1:953542119429:web:92541077fe70195ff24c6c',
    messagingSenderId: '953542119429',
    projectId: 'spotable-30891',
    authDomain: 'spotable-30891.firebaseapp.com',
    storageBucket: 'spotable-30891.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYEnGtA5uk_f4ZCrVW_cqoexuagWjk7wA',
    appId: '1:953542119429:android:2d75a3a58894593cf24c6c',
    messagingSenderId: '953542119429',
    projectId: 'spotable-30891',
    storageBucket: 'spotable-30891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBiFVoq0jywJOkF00n5F9D06VJKEsiog',
    appId: '1:953542119429:ios:965cb00c3c003333f24c6c',
    messagingSenderId: '953542119429',
    projectId: 'spotable-30891',
    storageBucket: 'spotable-30891.firebasestorage.app',
    iosBundleId: 'com.example.spotableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBiFVoq0jywJOkF00n5F9D06VJKEsiog',
    appId: '1:953542119429:ios:965cb00c3c003333f24c6c',
    messagingSenderId: '953542119429',
    projectId: 'spotable-30891',
    storageBucket: 'spotable-30891.firebasestorage.app',
    iosBundleId: 'com.example.spotableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6oR1BkXqqWpeX9-zBl5O_NjDG2DCdB8',
    appId: '1:953542119429:web:95d39d5b211b123ef24c6c',
    messagingSenderId: '953542119429',
    projectId: 'spotable-30891',
    authDomain: 'spotable-30891.firebaseapp.com',
    storageBucket: 'spotable-30891.firebasestorage.app',
  );
}
